"""
Calibration Service & Validation Runner — Pod 2
================================================
Compares benchmark answers (stratified sample from Mohler ASAG dataset +
handwritten behavioral answers) against fused scores generated by the
scoring pipeline, calculating Pearson and Spearman correlation statistics.
"""

from typing import List, Dict, Any, Optional
from pathlib import Path
import json
import threading
import numpy as np
from scipy.stats import pearsonr, spearmanr
from app.services.scoring import score_answer


DATASET_PATH = Path(__file__).parent / "calibration_dataset.json"

# In-memory cache — populated once, reused on every subsequent request.
_calib_cache: Optional[Dict[str, Any]] = None
_calib_lock = threading.Lock()


def load_benchmark_dataset() -> List[Dict[str, Any]]:
    if DATASET_PATH.exists():
        with open(DATASET_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


BENCHMARK_DATASET: List[Dict[str, Any]] = load_benchmark_dataset()


def get_cached_coefficients() -> Optional[Dict[str, float]]:
    """
    Return cached linear regression coefficients instantly if available.
    Returns None if the cache hasn't been warmed yet.
    """
    if _calib_cache is not None:
        return {
            "linear_slope": _calib_cache["linear_slope"],
            "linear_intercept": _calib_cache["linear_intercept"],
            "pearson_r": _calib_cache["pearson_r"],
            "spearman_rho": _calib_cache["spearman_rho"],
            "sample_count": _calib_cache["sample_count"],
        }
    return None


def pre_warm_calibration_cache() -> None:
    """
    Run calibration in background at startup so the first user request
    gets an instant response. Safe to call from a daemon thread.
    """
    try:
        run_calibration_check()
    except Exception:
        pass  # non-fatal — page degrades gracefully


def run_calibration_check() -> Dict[str, Any]:
    """
    Run calibration check against benchmark dataset.
    Returns dictionary with pearson_r, spearman_rho, sample_count,
    linear_slope, linear_intercept, top_disagreements, and itemized results.
    Results are cached in memory so subsequent calls return instantly.
    """
    global _calib_cache

    # Serve from cache if already computed
    with _calib_lock:
        if _calib_cache is not None:
            return _calib_cache

    dataset = load_benchmark_dataset() if not BENCHMARK_DATASET else BENCHMARK_DATASET
    human_scores = []
    fused_scores = []
    itemized = []

    for item in dataset:
        res = score_answer(
            answer_text=item["student_answer"],
            reference_answer=item["reference_answer"],
            question_text=item["question_text"]
        )

        h_score = float(item["human_score"])
        f_score = float(res["fused_score"])

        human_scores.append(h_score)
        fused_scores.append(f_score)

        item_entry = {
            "question": item["question_text"],
            "reference_answer": item.get("reference_answer", ""),
            "student_answer": item["student_answer"],
            "human_score": h_score,
            "fused_score": f_score,
            "score_diff": round(abs(h_score - f_score), 4),
            "source": item.get("source", "mohler"),
            "similarity_score": res["similarity_score"],
            "concept_match_score": res["concept_match_score"],
            "llm_judge_score": res["llm_judge_score"],
            "missing_keywords": res.get("missing_keywords", []),
        }
        itemized.append(item_entry)

    pearson_corr, p_val = pearsonr(human_scores, fused_scores)
    spearman_corr, sp_val = spearmanr(human_scores, fused_scores)

    # Origin-constrained regression: human_score = slope * fused_score
    # Forced through origin so predicted_human is 0 when fused_score is 0.
    # slope = dot(fused, human) / dot(fused, fused)
    fs = np.array(fused_scores)
    hs = np.array(human_scores)
    slope = float(np.dot(fs, hs) / np.dot(fs, fs)) if np.dot(fs, fs) > 0 else 1.0

    sorted_disagreements = sorted(itemized, key=lambda x: x["score_diff"], reverse=True)

    result = {
        "sample_count": len(dataset),
        "pearson_r": round(float(pearson_corr), 4),
        "pearson_p_value": round(float(p_val), 4),
        "spearman_rho": round(float(spearman_corr), 4),
        "spearman_p_value": round(float(sp_val), 4),
        "linear_slope": round(float(slope), 6),
        "linear_intercept": 0.0,
        "top_disagreements": sorted_disagreements[:5],
        "itemized": itemized,
    }

    with _calib_lock:
        _calib_cache = result

    return result


if __name__ == "__main__":
    metrics = run_calibration_check()
    print("=== Pod 2 Calibration Validation Results ===")
    print(f"Sample count: {metrics['sample_count']}")
    print(f"Pearson Correlation (r): {metrics['pearson_r']} (p={metrics['pearson_p_value']})")
    print(f"Spearman Correlation (rho): {metrics['spearman_rho']} (p={metrics['spearman_p_value']})")
    print("\nTop 5 Disagreements:")
    for i, d in enumerate(metrics['top_disagreements'], 1):
        print(f"  {i}. [{d['source']}] Human: {d['human_score']:.2f} vs Fused: {d['fused_score']:.2f} (gap: {d['score_diff']:.2f})")
        print(f"     Q: {d['question']}")
        print(f"     A: {d['student_answer']}")
