"""
Calibration Service & Validation Runner — Pod 2
================================================
Compares benchmark answers (stratified sample from Mohler ASAG dataset +
handwritten behavioral answers) against fused scores generated by the
scoring pipeline, calculating Pearson and Spearman correlation statistics.
"""

from typing import List, Dict, Any
from pathlib import Path
import json
from scipy.stats import pearsonr, spearmanr
from app.services.scoring import score_answer


DATASET_PATH = Path(__file__).parent / "calibration_dataset.json"


def load_benchmark_dataset() -> List[Dict[str, Any]]:
    if DATASET_PATH.exists():
        with open(DATASET_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


BENCHMARK_DATASET: List[Dict[str, Any]] = load_benchmark_dataset()


def run_calibration_check() -> Dict[str, Any]:
    """
    Run calibration check against benchmark dataset.
    Returns dictionary with pearson_r, spearman_rho, sample_count, top_disagreements, and itemized results.
    """
    dataset = load_benchmark_dataset() if not BENCHMARK_DATASET else BENCHMARK_DATASET
    human_scores = []
    fused_scores = []
    itemized = []

    for item in dataset:
        res = score_answer(
            answer_text=item["student_answer"],
            reference_answer=item["reference_answer"],
            question_text=item["question_text"]
        )

        h_score = float(item["human_score"])
        f_score = float(res["fused_score"])

        human_scores.append(h_score)
        fused_scores.append(f_score)

        item_entry = {
            "question": item["question_text"],
            "reference_answer": item.get("reference_answer", ""),
            "student_answer": item["student_answer"],
            "human_score": h_score,
            "fused_score": f_score,
            "score_diff": round(abs(h_score - f_score), 4),
            "source": item.get("source", "mohler"),
            "similarity_score": res["similarity_score"],
            "concept_match_score": res["concept_match_score"],
            "llm_judge_score": res["llm_judge_score"],
            "missing_keywords": res.get("missing_keywords", []),
        }
        itemized.append(item_entry)

    pearson_corr, p_val = pearsonr(human_scores, fused_scores)
    spearman_corr, sp_val = spearmanr(human_scores, fused_scores)

    # 5 largest |human_score - fused_score| gaps, sorted descending
    sorted_disagreements = sorted(itemized, key=lambda x: x["score_diff"], reverse=True)
    top_disagreements = sorted_disagreements[:5]

    return {
        "sample_count": len(dataset),
        "pearson_r": round(float(pearson_corr), 4),
        "pearson_p_value": round(float(p_val), 4),
        "spearman_rho": round(float(spearman_corr), 4),
        "spearman_p_value": round(float(sp_val), 4),
        "top_disagreements": top_disagreements,
        "itemized": itemized,
    }


if __name__ == "__main__":
    metrics = run_calibration_check()
    print("=== Pod 2 Calibration Validation Results ===")
    print(f"Sample count: {metrics['sample_count']}")
    print(f"Pearson Correlation (r): {metrics['pearson_r']} (p={metrics['pearson_p_value']})")
    print(f"Spearman Correlation (rho): {metrics['spearman_rho']} (p={metrics['spearman_p_value']})")
    print("\nTop 5 Disagreements:")
    for i, d in enumerate(metrics['top_disagreements'], 1):
        print(f"  {i}. [{d['source']}] Human: {d['human_score']:.2f} vs Fused: {d['fused_score']:.2f} (gap: {d['score_diff']:.2f})")
        print(f"     Q: {d['question']}")
        print(f"     A: {d['student_answer']}")
