"""
Calibration Service & Validation Runner — Pod 2
================================================
Compares hand-rated gold benchmark answers against fused scores generated by the
3-signal scoring pipeline, calculating Pearson and Spearman correlation statistics.
"""

from typing import List, Dict, Any
from scipy.stats import pearsonr, spearmanr
from app.services.scoring import score_answer


BENCHMARK_DATASET: List[Dict[str, Any]] = [
    {
        "question_text": "How do you detect a cycle in a singly linked list?",
        "reference_answer": "Use Floyd's Cycle-Finding Algorithm (Fast and Slow Pointers). Initialize two pointers, one moving one step and the other two steps.",
        "student_answer": "Use fast and slow pointers. If they meet, there is a cycle.",
        "human_score": 0.90,
    },
    {
        "question_text": "How do you detect a cycle in a singly linked list?",
        "reference_answer": "Use Floyd's Cycle-Finding Algorithm (Fast and Slow Pointers). Initialize two pointers, one moving one step and the other two steps.",
        "student_answer": "Use a hash set to store visited node addresses as you traverse.",
        "human_score": 0.75,
    },
    {
        "question_text": "How do you detect a cycle in a singly linked list?",
        "reference_answer": "Use Floyd's Cycle-Finding Algorithm (Fast and Slow Pointers). Initialize two pointers, one moving one step and the other two steps.",
        "student_answer": "Sort the linked list using quicksort and check adjacent elements.",
        "human_score": 0.20,
    },
    {
        "question_text": "Explain the trade-offs between SQL and NoSQL databases.",
        "reference_answer": "SQL databases are structured, ACID-compliant, and scale vertically. NoSQL databases offer flexible schemas, horizontal scalability, and eventual consistency.",
        "student_answer": "SQL is relational with fixed schemas and ACID properties. NoSQL is non-relational and scales horizontally.",
        "human_score": 0.95,
    },
    {
        "question_text": "Explain the trade-offs between SQL and NoSQL databases.",
        "reference_answer": "SQL databases are structured, ACID-compliant, and scale vertically. NoSQL databases offer flexible schemas, horizontal scalability, and eventual consistency.",
        "student_answer": "SQL is faster for everything and NoSQL is just for small projects.",
        "human_score": 0.25,
    },
    {
        "question_text": "Describe a situation where you had a disagreement with a team member.",
        "reference_answer": "Use the STAR method: active listening, evaluating data/criteria objectively, remaining professional, reaching collaborative consensus.",
        "student_answer": "I listened to their perspective, presented benchmark data objectively, and we compromised on a hybrid approach.",
        "human_score": 0.90,
    },
    {
        "question_text": "Describe a situation where you had a disagreement with a team member.",
        "reference_answer": "Use the STAR method: active listening, evaluating data/criteria objectively, remaining professional, reaching collaborative consensus.",
        "student_answer": "I proved I was right and told them to follow my plan.",
        "human_score": 0.30,
    },
]


def run_calibration_check() -> Dict[str, Any]:
    """
    Run calibration check against benchmark dataset.
    Returns dictionary with pearson_r, spearman_rho, sample_count, and itemized results.
    """
    human_scores = []
    fused_scores = []
    itemized = []

    for item in BENCHMARK_DATASET:
        res = score_answer(
            answer_text=item["student_answer"],
            reference_answer=item["reference_answer"],
            question_text=item["question_text"]
        )

        h_score = float(item["human_score"])
        f_score = float(res["fused_score"])

        human_scores.append(h_score)
        fused_scores.append(f_score)

        itemized.append({
            "question": item["question_text"],
            "student_answer": item["student_answer"],
            "human_score": h_score,
            "fused_score": f_score,
            "similarity_score": res["similarity_score"],
            "concept_match_score": res["concept_match_score"],
            "llm_judge_score": res["llm_judge_score"],
            "missing_keywords": res["missing_keywords"],
        })

    pearson_corr, p_val = pearsonr(human_scores, fused_scores)
    spearman_corr, sp_val = spearmanr(human_scores, fused_scores)

    return {
        "sample_count": len(BENCHMARK_DATASET),
        "pearson_r": round(float(pearson_corr), 4),
        "pearson_p_value": round(float(p_val), 4),
        "spearman_rho": round(float(spearman_corr), 4),
        "spearman_p_value": round(float(sp_val), 4),
        "itemized": itemized,
    }


if __name__ == "__main__":
    metrics = run_calibration_check()
    print("=== Pod 2 Calibration Validation Results ===")
    print(f"Sample count: {metrics['sample_count']}")
    print(f"Pearson Correlation (r): {metrics['pearson_r']} (p={metrics['pearson_p_value']})")
    print(f"Spearman Correlation (rho): {metrics['spearman_rho']} (p={metrics['spearman_p_value']})")
